export enum EventCode {
  // User Events
  USER_LOGIN = 'EVT_USER_LOGIN',
  USER_LOGOUT = 'EVT_USER_LOGOUT',
  USER_SIGNUP = 'EVT_USER_SIGNUP',
  USER_PROFILE_UPDATE = 'EVT_USER_PROFILE_UPDATE',

  // Cart & Checkout Events
  CART_ADD = 'EVT_CART_ADD',
  CART_REMOVE = 'EVT_CART_REMOVE',
  CHECKOUT_SUCCESS = 'EVT_CHECKOUT_SUCCESS',
  CHECKOUT_FAILURE = 'EVT_CHECKOUT_FAILURE',

  // API Events
  API_FAILURE = 'EVT_API_FAILURE',
  API_SUCCESS = 'EVT_API_SUCCESS',

  // Product Events
  PRODUCT_VIEW = 'EVT_PRODUCT_VIEW',
  PRODUCT_PURCHASE = 'EVT_PRODUCT_PURCHASE',
  PRODUCT_FETCH_SUCCESS = 'EVT_PRODUCT_FETCH_SUCCESS',
  PRODUCT_FETCH_FAILURE = 'EVT_PRODUCT_FETCH_FAILURE',

  // Error Events
  ERROR_UNAUTHORIZED = 'EVT_ERROR_UNAUTHORIZED',
  ERROR_NOT_FOUND = 'EVT_ERROR_NOT_FOUND',
  ERROR_SERVER = 'EVT_ERROR_SERVER',

  // Navigation Events
  PAGE_VIEW_HOME = 'EVT_PAGE_VIEW_HOME',
  PAGE_VIEW_PRODUCT = 'EVT_PAGE_VIEW_PRODUCT',
  PAGE_VIEW_CART = 'EVT_PAGE_VIEW_CART',

  // Discount Events
  DISCOUNT_APPLIED = 'EVT_DISCOUNT_APPLIED',
  DISCOUNT_RESET = 'EVT_DISCOUNT_RESET',
}
